### ISSUE TITLE
Listen to componentWillReceiveProps

### ISSUE THREAD

**Issue by williamboman** [jakezatecky/react-checkbox-tree#10]
Had some issues figuring this component out, took quite some time to debug an issue I had with breaking object references due to fetching new data to be displayed in the checkbox tree from an API.

**Comment by jakezatecky** [comment]
Not quite sure what issues you were experiencing, but do they still occur in the v0.3.0 release candidate? There certainly were issues with properties having their values mutate when they should not have.
