### ISSUE TITLE
Ability to style collapsed parent node

### ISSUE THREAD

**Issue by smoothpie** [jakezatecky/react-checkbox-tree#114]
Hi, thanks for the lib!
I'm currently trying to style collapsed parent node and can't seem to find a way to do this, since collapsing doesn't change anything except for appending a child list, and there're still no elegant parent selector solutions out there :) Would be great if, for example, 'collapsed' class was added to parent node. Or, please, guide me if I'm missing something. Thanks!

**Comment by jakezatecky** [comment]
Yes, I do not think there is any way to get the parent via CSS selectors. Therefore, I added `rct-node-expanded` and `rct-node-collapsed` classes to the parent node as appropriate. This is available on v1.4.0, which was published moments ago.
