### ISSUE TITLE
Usage with react-fontawesome

### ISSUE THREAD

**Issue by austinbutler** [jakezatecky/react-checkbox-tree#115]
I see this project is using FontAwesome 4 via directly adding the CSS for it. In my case, I was already using the official [`react-fontawesome`](https://github.com/FortAwesome/react-fontawesome) library (since it can bundle only the icons you explicitly import instead of all of them), and of course I didn't want the whole FontAwesome bundle included a second time.

It took a bit of looking up the FontAwesome codes in the CSS included with `react-checkbox-tree`, so I'm pasting the icon config I came up with that replicates the `react-checkbox-tree` examples. Hopefully this is helpful to others, and maybe you want to add it to the README.

```js
const icons = {
  check: <FontAwesomeIcon className='rct-icon rct-icon-check' icon='check-square' />,
  uncheck: <FontAwesomeIcon className='rct-icon rct-icon-uncheck' icon={['far', 'square']} />,
  halfCheck: <FontAwesomeIcon className='rct-icon rct-icon-half-check' icon='check-square' />,
  expandClose: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='chevron-right' />,
  expandOpen: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='chevron-down' />,
  expandAll: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='plus-square' />,
  collapseAll: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='minus-square' />,
  parentClose: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='folder' />,
  parentOpen: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='folder-open' />,
  leaf: <FontAwesomeIcon className='rct-icon rct-icon-expand-close' icon='file' />
}
```

**Comment by dcollins98** [comment]
Half check shows wrong icon (check-square).

**Comment by jakezatecky** [comment]
@dcollins98 It should be the same icon as a checked boxed. The only difference is opacity.
