### ISSUE TITLE
Dynamically enable or disable component

### ISSUE THREAD

**Issue by bunkdeath** [jakezatecky/react-checkbox-tree#119]
The current implementation does not allow me to enable the component which has been loaded disabled by default programmatically or vice-versa

**Comment by Kdoggett887** [comment]
Looks like the `disabled` property on nodes can be dynamically assigned. Depending on how your tree is generated this might not be too hard of a workaround to implement.

**Comment by yp** [comment]
That's true, but it is quite hard to maintain. Personally I preferred to stick with `v1.2.4`.
