### ISSUE TITLE
The halfCheck-checkbox selects (unselects) all hierarchy nodes only after 2 clicks in IE, Edge browsers

### ISSUE THREAD

**Issue by OPEOP** [jakezatecky/react-checkbox-tree#120]
Steps to reproduce:

Open reactCheckboxTree component in IE or Edje.

Select one nested item in the tree;
Click on a higher checkbox in a hierarchy to select all nodes.

Actual result:
The checkbox is still in the half-checked state after 1 click. Only after the second click, it is selected all inner nodes and this half-checked checkbox changed its state.

Expected result:
The half-checked checkbox must select all internal nodes after 1 click and change its state.

**Comment by jakezatecky** [comment]
Confirmed.

**Comment by jakezatecky** [comment]
Thanks for the report. IE/Edge treat indeterminate (half-check) states different than other browsers when DOM events are fired. Luckily, the solution did not require significant change.
