### ISSUE TITLE
onChecked provide more meta data, such as level

### ISSUE THREAD

**Issue by evbo** [jakezatecky/react-checkbox-tree#122]
Would you consider the enhancement of returning the level and index of what was checked when `onChecked` is triggered? This way, I know easily how to operate on the data based on where in the tree it's located.

For instance, knowing if it's the top parent, or the 2nd child branch would tell me to run certain actions differently. Let's say the top parent is countries and the children are cities. I may want to run an action for displaying country information when one of those are checked, etc.

Currently I map the value checked to lists I store for each level. It's a lot of extra state to carry around, so was hopeful your api could store more information about each node, or at least return what hierarch level was checked during onChecked.

**Comment by jakezatecky** [comment]
I suppose it would not take too much effort to add this metadata information in.
