### ISSUE TITLE
Tree don't render

### ISSUE THREAD

**Issue by giorgi-m** [jakezatecky/react-checkbox-tree#136]
The tree don't seem to be rendered properly: https://codesandbox.io/s/30r97o23x5
I basically copy pasted the example from your page. Maybe it is a codesandbox thing ...

**Comment by jakezatecky** [comment]
Interesting. What you have on CodeSandbox *should* have worked, but it appears that the `<link>` for Font Awesome spits out a console error when the `integrity` attribute is provided:

```
None of the “sha384” hashes in the integrity attribute match the content of the subresource.
```

It seems that there is a integrity mismatch or the browser for whatever reason is not playing nicely with it. Simply removing that attribute (and reloading the page) causes the icons to render. See the below fork where I modified the Font Awesome `<link>`.

https://codesandbox.io/s/1y4rwpwoxl

**Comment by giorgi-m** [comment]
ok, thanks, I see.
