### ISSUE TITLE
Poor performance on large number of nodes

### ISSUE THREAD

**Issue by jakezatecky** [jakezatecky/react-checkbox-tree#14]
The tree suffers from poor performance when checking a parent with many nodes. Since those nodes are not necessarily rendered when collapsed, this should not be the case. Likely will be improved with stateless conversion (#12).

**Comment by jakezatecky** [comment]
Although some recent improvements were made, the performance is still kind of bad on large number of nodes.

**Comment by SirGordon** [comment]
planning to use https://github.com/bvaughn/react-virtualized ?

**Comment by jakezatecky** [comment]
@SirGordon I am not sure if that applies, as the performance bottleneck here is not on the rendered components per se, but on the computations it takes to traverse children on check state updates and retrievals.

**Comment by jakezatecky** [comment]
This issue was caused by O(n*n) performance, due to iterating through the `checked` and `expanded` arrays for each node. A more optimized version exists that flattens the `nodes` array and each node now checks against its mapped value.
