### ISSUE TITLE
Basic example is not working as expected

### ISSUE THREAD

**Issue by vkosovskikh** [jakezatecky/react-checkbox-tree#144]
Just trying to run basic example. Checkboxes are not becoming checked after click. Method `onCheck = checked => { this.setState({ checked }) }` gets an array with only one id of last clicked checkbox.

If initial state includes some `checked` elements, they are displayed as checked, but again after clicking nothing happens.

**Comment by vkosovskikh** [comment]
Found the last working version `@1.4.1`

**Comment by jakezatecky** [comment]
Hello @vkosovskikh. I am currently unable to replicate this issue. I have created a reference point of the latest version of the library that uses a (lightly) modified version of the code on the README page:

https://codesandbox.io/s/1z9yny5473

Can you try to create a live example that replicates the behavior you are experiencing? You can modify the sandbox above or use some other similar site that showcases the issue.

**Comment by vkosovskikh** [comment]
Yeah, lib is working fine on new projects. And I got lib working in my project after some manipulations with npm packages. Dunno what was the actual reason of not working last version. Anyway, sorry for fake issue.

**Comment by jakezatecky** [comment]
Glad to hear it is working for you.

**Comment by kishorebovi** [comment]
I am also facing the same issue in the latest version. But is working fine in v1.4.1. Don't know what exactly is the problem. @vkosovskikh  Can you let me know what manipulations you made in npm packages.

**Comment by vkosovskikh** [comment]
@kishorebovi Firstly, I checked that last version is working in project created by create-react-app. After that in my main project I tried different React versions. From 16.2 to 16.3 - didn't work. From 16.3 to 16.8 - didn't work. Than back to 16.2 and it suddenly began to work. Also I tried to remove node_modules and install all again.

**Comment by kishorebovi** [comment]
@vkosovskikh Thanks for the quick reply. So basically you changed the react version. But I am using react v15.6.2 and I can't change the version since it is a live project. @jakezatecky any help on this issue would be great.

**Comment by jakezatecky** [comment]
@kishorebovi It is hard to provide any help without a minimal live example showcasing this issue (such as the one I created above).
