### ISSUE TITLE
Show node children count appended in the label

### ISSUE THREAD

**Issue by mikevercoelen** [jakezatecky/react-checkbox-tree#161]
Does anyone have a suggestion on adding a node's label how how many children a node contains.

For example:

- Europe (7)
- Benelux (3)

etc.

**Comment by jakezatecky** [comment]
There is no such feature in the component itself but you could recursively iterate through the nodes yourself to append those counts. Would that reasonably suit your needs?

``` js
function appendCount(nodes) {
  return nodes.map((node, index) => {
    if (node.children) {
      node.label += ` (${node.children.length})`;
      node.children = appendCount(node.children);
    }
    return node;
  });
}
```
