### ISSUE TITLE
Error in plugin "gulp-exec"

### ISSUE THREAD

**Issue by Suvitruf** [jakezatecky/react-checkbox-tree#166]
1. Download project.
2. Try to build.
3. Error.

```
[19:55:15] Finished 'build-style' after 1.05 s
[19:55:15] Starting '<anonymous>'...
[19:55:15] '<anonymous>' errored after 17 ms
[19:55:15] Error in plugin "gulp-exec"
Message:
    Command failed: cmp .css-compare/less/react-checkbox-tree.css .css-compare/scss/react-checkbox-tree.css
"cmp" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

Details:
    killed: false
    code: 1
    signal: null
    cmd: cmp .css-compare/less/react-checkbox-tree.css .css-compare/scss/react-checkbox-tree.css
    domainEmitter: [object Object]
    domainThrown: false

[19:55:15] 'compare-css-output' errored after 1.07 s
[19:55:15] 'build' errored after 8.65 s
```

**Comment by jakezatecky** [comment]
Is this related to [your comment](https://github.com/jakezatecky/react-checkbox-tree/issues/146#issuecomment-525849998) about Ruby? I removed and reinstalled all npm packages and the main build succeeded for me.

**Comment by Suvitruf** [comment]
Which OS did you try it on? I've tried it on Win7.

**Comment by jakezatecky** [comment]
I ran it on a Windows 10 machine. Note that the Windows command line will not work as `cmp` is not a valid command. Using Git Bash or a similar Unix-like shell should make the build work as expected.

**Comment by jakezatecky** [comment]
Closing the issue due to lack of activity. Please let me know if the error still persists when running Git Bash or a similar Unix shell!
