### ISSUE TITLE
I want to add some icons on the right of the nodes, what should I do? Thanks

### ISSUE THREAD

**Issue by lpf260** [jakezatecky/react-checkbox-tree#170]
for example add a insert icon

**Comment by jakezatecky** [comment]
Sorry for the late reply.

You can make the `label` property of a node be a React element such that an icon could exist after the text:

``` jsx
const nodes = [{
  value: 'bed',
  label: (
    <span>
      bed
      <i className="fa fa-bed" />
    </span>
  ),
}];

return <CheckboxTree nodes={nodes} />;
```

Let me know if this does not work for you.

**Comment by vandanachadha** [comment]
@jakezatecky When I do the above and pass it from backend  controller to a react component, the html gets printed as is, and doesnt render.
![image](https://user-images.githubusercontent.com/982568/124900024-4eb36900-dffe-11eb-903b-6b2275bee554.png)


backend code is:
       let leaf = {
          leaf: true,
          label: obj.devices[i],
          value: obj.deviceIds[i],
          icon: `<i className="rct-icon rct-icon-check" />`
        }

**Comment by jakezatecky** [comment]
@vandanachadha content inside of backtick characters (`` ` ``) will be treated as strings in JavaScripts, which it looks like is happening for you. Remove those backticks and those icons should be treated as JSX elements.

**Comment by vandanachadha** [comment]
Bit without the backticks, I cannot add the object to an array in js at node side and push it to frontend on react

Sent from Yahoo Mail on Android 
 
  On Thu, 8 Jul 2021 at 9:25 PM, Jake ***@***.***> wrote:   


@vandanachadha content inside of backtick characters (`) will be treated as strings in JavaScripts, which it looks like is happening for you. Remove those backticks and those icons should be treated as JSX elements.

**Comment by vandanachadha** [comment]
@jakezatecky Problem is that I am making this object in the backend and sending to react. And without the backticks, I cannot add the object to an array in js at node side.

**Comment by jakezatecky** [comment]
It sounds like you need to have the front-end create the `icon` JSX element, rather than merely passing through from your backend code. This component does not allow raw HTML strings for any of its properties.
