### ISSUE TITLE
can not find a way to display Empty Folder. 

### ISSUE THREAD

**Issue by ANANDKNIT** [jakezatecky/react-checkbox-tree#171]
I want to render Empty Folders in this tree. 
![Selection_001](https://user-images.githubusercontent.com/42730462/66645669-b24e0e00-ec41-11e9-9f77-18b99e65ee7d.png)
Instead of folder icon I am getting file icon

**Comment by GuyPaddock** [comment]
Just submitted a PR for this issue; ran into it myself.

As a workaround, I think it's possible to ensure that "empty" nodes have at least one child that just has a label of "Empty folder" with `showCheckbox` set to `false`.
