### ISSUE TITLE
Demo is not visually reproducible

### ISSUE THREAD

**Issue by Ploppz** [jakezatecky/react-checkbox-tree#191]
I wanted to reproduce the look of react-checkbox-tree as in the gif here https://www.npmjs.com/package/react-checkbox-tree

But when I paste the code on that page into codesandbox, I get something quite different:
https://codesandbox.io/s/vibrant-tdd-u5n0j
The neat arrows have become weird elongated button-like entities.

**Comment by Ploppz** [comment]
sorry, I skipped the CSS section.
`import 'react-checkbox-tree/lib/react-checkbox-tree.css';`

**Comment by cvzbynek** [comment]
I have the same issue and I haven't skipped the CSS section
