### ISSUE TITLE
add feature to change hint/tooltip

### ISSUE THREAD

**Issue by normanaranez** [jakezatecky/react-checkbox-tree#193]
change hint/tooltip props text for the toggle, expand all and collapse all

**Comment by jakezatecky** [comment]
This points to a need for a `lang` object to support changing the text of all static text. This will be straightforward to implement.

**Comment by Marfa93** [comment]
Hello! Do we have any news on this feature ?
I am very interested in this 😊

**Comment by jakezatecky** [comment]
This is accessible via the `lang` property now (see [this line](https://github.com/jakezatecky/react-checkbox-tree/blob/master/src/js/CheckboxTree.jsx#L68) for the default properties).

However, v2.0 is underway (no release date yet), and[ `toggle` will be renamed to `expandNode` and `collapseNode`](https://github.com/jakezatecky/react-checkbox-tree/blob/v2.0-dev/src/js/lang/default.js).
