### ISSUE TITLE
How can I have URL links on the leaves?

### ISSUE THREAD

**Issue by mericano1** [jakezatecky/react-checkbox-tree#194]
Hi there, great little library. Thanks for sharing.

Is there a way to have the leaves point to some URLs and onclick be disabled for those leaves ? 

I tried something like this but it didn't work

```
return {
    label: <a href={d.match.url}>d.match.title</a>,
    value: d.match.url
}
```

**Comment by mericano1** [comment]
nevermind, it does seem to work

**Comment by v4irajvimu** [comment]
how to do this?
@mericano1
