### ISSUE TITLE
Uncomplate typescript argument list for 'onCheck' propetry

### ISSUE THREAD

**Issue by croszatycki** [jakezatecky/react-checkbox-tree#208]
**Describe the bug**
Uncomplate typescript argument list for 'onCheck' propetry

**Reproduction steps**
In `react-checkbox-tree/src/index.d.ts:56` there is:
```ts
onCheck?: (checked: Array<string>) => void;
```
code triggers: `react-checkbox-tree/src/js/CheckboxTree.js:139` 
```js
        onCheck(model.serializeList('checked'), { ...node, ...nodeInfo });
```

**Expected behavior**
```ts
onCheck?: (checked: Array<string>, node: Node) => void;
```

**Comment by jakezatecky** [comment]
Thanks for reporting this.

The additional parameter is indeed missing from the TypeScript definition. However, the `node` argument for this function has one additional parameter not in the `Node` interface (`checked: boolean`). My TypeScript experience is very poor, but would the following new interface definition work?

``` typescript
interface OnCheckNode extends Node {
    checked: boolean;
}
```

If so, I can add that into `index.d.ts` and update `onCheck?` to include this interface.

**Comment by NZaljevic** [comment]
> Thanks for reporting this.
> 
> The additional parameter is indeed missing from the TypeScript definition. However, the `node` argument for this function has one additional parameter not in the `Node` interface (`checked: boolean`). My TypeScript experience is very poor, but would the following new interface definition work?
> 
> ```ts
> interface OnCheckNode extends Node {
>     checked: boolean;
> }
> ```
> 
> If so, I can add that into `index.d.ts` and update `onCheck?` to include this interface.

Yes, your suggested solution works similarly to the .jsx version.

**Comment by skoruba** [comment]
Could you please solve this issue? We have the exactly same problem with missing 2nd argument which is also missing on method called onExpand in typescript definitions.
Thanks!
