### ISSUE TITLE
Compilation on windows FAIL

### ISSUE THREAD

**Issue by franadoriv** [jakezatecky/react-checkbox-tree#218]
**Describe the bug**
This module is impossible to compile on windows.

**Reproduction steps**
yarn install
yarn build

**Expected behavior**
Build complete

**ERROR**
scss-lint : The term 'scss-lint' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ scss-lint
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scss-lint:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jakezatecky** [comment]
There is an additional build dependency not listed in the main README. I make note of it in the [examples](https://github.com/jakezatecky/react-checkbox-tree/tree/master/examples), but I should probably add it to the main README:

1, Install Ruby
2. Run `gem install sass scss_lint`

I have wanted to swap out `scsslint` for something else for a while, but the alternatives do not offer much feature parity. I might get to it eventually.

**Comment by jakezatecky** [comment]
42201348bca48d2a2ded5cf8596194741ac2ecc3 removed the build dependencies on Ruby and `scsslint` by switching to `stylelint`. No need to update documentation anymore.
