### ISSUE TITLE
Optionally make nodes of the tree 100% wide so that it's possible with right-aligned content

### ISSUE THREAD

**Issue by Ploppz** [jakezatecky/react-checkbox-tree#220]
I don't know if this is already possible but I couldn't make it work at least.
I would like to place some buttons at the very right on each node, so that they will be aligned nicely and separated visually from the label of each node.
The checkbox tree is in a container that has fixed width. So the way I envision this is that there should be an option to make the container of each node label extend fully (width = 100%) so that we can put a `<div style={{float: "right"}}>something</div>` in there that will all align perfectly to the right.

This is a screenshot when I currently try a div (with contents "Hey") that floats right:
![35 Monday-slop0861](https://user-images.githubusercontent.com/4773287/91726887-3afad300-eba1-11ea-880c-72641136346d.png)

And here is a demo that shows what I want, but with Material UI TreeView:
https://codesandbox.io/s/exciting-wood-kzzjx?file=/src/App.js

**Comment by jakezatecky** [comment]
This is possible with some CSS styling. See this [live example](https://codesandbox.io/s/react-checkbox-tree-example-forked-gnjpm?file=/src/index.js).

``` css
.rct-text label,
.rct-title {
  display: flex;
  align-items: center;
  width: 100%;
}

.rct-title button {
  margin-left: auto;
}

```

``` jsx

const nodes = [{
  value: 'mars',
  label: 'Mars',
  children: [
    {
      value: 'phobos',
      label: [
        <span key="label">Phobos</span>,
        <button key="button" type="button">Button 1</button>,
      ],
    },
    {
      value: 'deimos',
      label: [
        <span key="label">Deimos</span>,
        <button key="button" type="button">Button 2</button>,
      ],
    },
  ],
}];
```

**Comment by Ploppz** [comment]
Thanks!
