### ISSUE TITLE
Requirement for conditional enabling/disabling of checkboxes at the same level

### ISSUE THREAD

**Issue by Waqqars987** [jakezatecky/react-checkbox-tree#222]
Hi,

I have a requriement where I want a checkbox to be enabled only if the one before it is checked. Both of them are at the same level. Can someone tell me how to achieve this using react-checkbox-tree? Any help would be appreciated.

**Comment by jakezatecky** [comment]
There is not a native way to do this in the component, but you could do something like this:

``` js
function applyDisablingRules(nodes, checked) {
    let previous = null;
    
    return nodes.map((node, index) => {
        const previousIsChecked = previous !== null && checked.includes(node.value);
        const enabled = index === 0 || previousIsChecked;
        
        return {
            ...node,
            disabled: !enabled,
            children: applyDisablingRules(node.children, checked),
        };
    });
}

class Widget {
    ...

    render() {
        const { nodes, checked } = this.state;
        return <CheckboxTree nodes={applyDisablingRules(nodes, checked)} ... />;
    }
}
```

Note that this may have poor performance if you have a several `checked` nodes, as the `checked.includes` portion of the function results in `O(n^2)` performance for the entire function.

**Comment by Waqqars987** [comment]
I will try this out. Thanks a lot!
