### ISSUE TITLE
How to programatically check nodes?

### ISSUE THREAD

**Issue by mgcd3v** [jakezatecky/react-checkbox-tree#226]
Hi,

This is more of a question. I just want to know if there's a way to check just some nodes at runtime?

Thank you.

**Comment by muralimulagalapati** [comment]
If you have access to that node, set `checked: true` on that.

**Comment by mgcd3v** [comment]
Already solved. Still, thanks for the answer :)

**Comment by jakezatecky** [comment]
Closing due to resolved question.
