### ISSUE TITLE
'onCheck' function does not accept the 2nd argument

### ISSUE THREAD

**Issue by moc89** [jakezatecky/react-checkbox-tree#235]
**Describe the bug**
'onCheck' function does not accept the 2nd argument. I get an TypeScript error when I try to access targetNode as the 2nd parameter. Example below;

```
const onCheck = (checked:any, targetNode:any) => {
  }
```

But If I use like below it works properly and I don't get TypeScript error and it works.

**Reproduction steps**
Please include the necessary steps to reproduce the issue as well as a live example that showcases it. You can modify this [CodeSandbox reference point](https://codesandbox.io/s/oj5wnyr7w9) to create a working example.

**Expected behavior**
I need to access checked Node but In this case, I can access just checked value.

**Screenshots**

**Comment by jakezatecky** [comment]
This is a [known issue](https://github.com/jakezatecky/react-checkbox-tree/issues/208) with the TypeScript definition for this library. 

Could you look at my comment and confirm whether my suggestion would be appropriate to add as a second parameter for the `onCheck` function? I do not use TypeScript personally, but am fine with updating definitions so long as they are easy to maintain.

**Comment by arvind0364** [comment]
Is this issue fixed for typescript support.?

**Comment by jakezatecky** [comment]
It is, but a stable version has not be released. You can utilize the fix by pointing your `package.json` to commit 041f91dcceb64032b13ce2852fe0da1c988cb588, which includes fixes for both `onCheck` and `onExpand`.

**Comment by arvind0364** [comment]
That's great how do I point my (package.json) to that commit can you brief this a bit more.I have no idea about it.But I badly need this feature.

**Comment by jakezatecky** [comment]
Something like:

``` json
{
  "react-checkbox-tree": "git+https://github.com/jakezatecky/react-checkbox-tree.git#041f91dcceb64032b13ce2852fe0da1c988cb588"
}
```
