### ISSUE TITLE
when children:[] onCheck is not working

### ISSUE THREAD

**Issue by huudatk53** [jakezatecky/react-checkbox-tree#243]
My result nodes[] from api like img, or when i create nodes like this, onCheck is not working
![image](https://user-images.githubusercontent.com/13384935/102697420-39e0d500-4268-11eb-9859-7177ede0cf56.png)

![error](https://user-images.githubusercontent.com/13384935/102697399-1e75ca00-4268-11eb-80fa-0eaa95bef93c.gif)

**Comment by elcirao** [comment]
if children is `null` instead of an array, it should works

**Comment by jakezatecky** [comment]
The suggestion by @elcirao is good. You should have children set to `null` if you do not have any.

**Comment by huudatk53** [comment]
I got it, tks 👍
