### ISSUE TITLE
Show until specific level in tree

### ISSUE THREAD

**Issue by elcirao** [jakezatecky/react-checkbox-tree#244]
Please include a clear and concise description of the feature or enhancement you would like to have added to the project.
Hi, is there a way to show until specific leven in the tree? For example, i have an array with four levels from the API, but i just want to show until the third level. Is that possible?

**Comment by jakezatecky** [comment]
To be clear, are you looking for something to expand all of the nodes until the third level? This is a reasonable enough request, but it can be done through the `expanded` property, by iterating recursively through nodes until the desired depth is reached.

I can potentially add a utility function to help set that initial state.

**Comment by elcirao** [comment]
yes, i want expand all of the nodes until the third level :)

**Comment by jakezatecky** [comment]
For the interim, you can do something like the following. Note that the first level starts with 0:

``` js
function expandNodesToLevel(nodes, targetLevel, currentLevel = 0) {
  if (currentLevel > targetLevel) {
    return [];
  }

  let expanded = [];
  nodes.forEach((node) => {
    expanded.push(node.value);
    if (node.children) {
    	expanded = [...expanded, ...expandNodesToLevel(node.children, targetLevel, currentLevel + 1)];
    }
  });
  return expanded;
}
```

See the following [example](https://codesandbox.io/s/react-checkbox-tree-example-forked-umk6w) that expands the tree to the second level.

**Comment by elcirao** [comment]
it works perfect!
