### ISSUE TITLE
Uncaught TypeError: e[n].forEach is not a function

### ISSUE THREAD

**Issue by Clementol** [jakezatecky/react-checkbox-tree#246]
**Uncaught TypeError: e[n].forEach is not a function**
The main tree is working but to show the children is the problem following the example at npm website

**Expected to show sub tree**
 I expected drop down to show

**Comment by WBucci** [comment]
Im getting the same issue, but someone on my team has it working. Copying his code doesnt resolve my issue

**Comment by jakezatecky** [comment]
Can you link to a live version which shows this issue, using this [CodeSandbox reference point](https://codesandbox.io/s/oj5wnyr7w9) as a base?

**Comment by nour-sidaoui** [comment]
I got this error when I tried to use the library as a function.
BTW, is it possible to use it as a function instead of class? an example would be appreciated a lot :)

**Comment by glxdsunname** [comment]
i got this issue when i use hooks in checked and expanded:  checked => setChecked( { checked });

**Comment by jakezatecky** [comment]
That is possible error others may be experiencing. The `checked`, `expanded`, and `nodes` property should all be Arrays.

**Comment by jakezatecky** [comment]
Since the docs all reference functional/hook usage now, this should no longer be confusing to developers without class experience.
