### ISSUE TITLE
Uncomplate typescript argument list for 'onExpand' propetry

### ISSUE THREAD

**Issue by skoruba** [jakezatecky/react-checkbox-tree#248]
In the typescript definition is also missing argument for method `onExpand` - could you please add the similar fix for onExpand method like you did on onCheck here - https://github.com/jakezatecky/react-checkbox-tree/commit/b144261273bf3107ee468d9fd6dd52e116fe93ee

Thanks!

**Comment by skoruba** [comment]
When do you plan to publish new package to npm? All changes from master branch?

**Comment by jakezatecky** [comment]
Undetermined, although I will likely shorten the scope for v1.7.0 and move some of the other items to a v1.8.0 release. Maybe within a week or two.

You can, if needed, point npm to the latest commit hash on the `v1.7-dev` branch if you want to take advantage of the current changes.

**Comment by skoruba** [comment]
Thanks! I didn't know that ability to use specific commit for npm. 👍
