### ISSUE TITLE
How Can  i check/uncheck all nodes ?

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [jakezatecky/react-checkbox-tree#251]
i need a button like open/collapse all in order to check all nodes, How can i do that?
i'll be glad if you can provide an example.
Thanks in Advance.

**Comment by jakezatecky** [comment]
There is a property, `showExpandAll`, that will add a button to the top right of the component and allows users to collapse and open all nodes. For checking/unchecking all nodes, the only way to do this would be to create a top level node that contains all other nodes.

An additional property, like `showCheckAll`, may be added in the future.

**Comment by MohammedSaberMohammed** [comment]
I made a Function to handle this logic

**Comment by JamesBrightman** [comment]
> I made a Function to handle this logic

Can you share that function? I'm also needing to select all the nodes. I like this library but it's very surprising to me that there isn't this option yet, as it's an extremely common use case.

**Comment by MohammedSaberMohammed** [comment]
@JamesBrightman 
Here is my component you can check the whole functionality

`
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
// Lodash
// import isEqual from 'lodash/isEqual';
// Animations
import Fade from 'react-reveal/Fade';
// Lib
import NestedCheckboxTree from 'react-checkbox-tree';
import 'react-checkbox-tree/lib/react-checkbox-tree.css';
// MUI
import InputLabel from '@material-ui/core/InputLabel';
import FormHelperText from '@material-ui/core/FormHelperText';
// Component
import { Checkbox } from './Checkbox';
// Services
import Strings from '~/Services/Strings';
// Icons
import KeyboardArrowLeftIcon from '@material-ui/icons/KeyboardArrowLeft';
import KeyboardArrowDownIcon from '@material-ui/icons/KeyboardArrowDown';
import CheckBoxIcon from '@material-ui/icons/CheckBox';
import CheckBoxOutlineBlankIcon from '@material-ui/icons/CheckBoxOutlineBlank';
import IndeterminateCheckBoxIcon from '@material-ui/icons/IndeterminateCheckBox';
class CheckboxTree extends React.Component {
  state = {
    expanded: [],
    isSelectAllChecked: false
  };

  componentDidMount() { 
    this.updateSelectAllCheckboxValue();
  }

  componentDidUpdate() { 
    this.updateSelectAllCheckboxValue();
  }

  updateSelectAllCheckboxValue = () => { 
    const { value } = this.props;
    const { isSelectAllChecked } = this.state;

    if ((value.length === this.nodesCount) && !isSelectAllChecked) {
      this.setState({ isSelectAllChecked: true });
    }

    if ((value.length !== this.nodesCount) && isSelectAllChecked) {
      this.setState({ isSelectAllChecked: false });
    }
  }

  handleChangeSelection = value => { 
    const { name, onChange } = this.props;

    if (name) {
      onChange(name, value);
    } else { 
      onChange(value);
    }
  }

  onSelectAllChange = isSelectAllChecked => {
    this.setState({ isSelectAllChecked: Boolean(isSelectAllChecked) }, () => {
      if (isSelectAllChecked) {
        this.selectAll();
      } else { 
        this.deselectAll();
      }
    });
  }

  selectAll = () => {
    // noCascade [ if true includes parent node in selection and viceversa ]
    const { nodes, noCascade } = this.props;
    const allValues = [];

    const valueExtracter = (structure = nodes) =>
      structure.forEach(node => {
        const isParentNode = node.hasOwnProperty('children');
        // if parent Node and [ parent should be included in selection ]
        // or if the node [ is Not Parent ] u should Append it
        if ((isParentNode && noCascade) || !isParentNode) {
          allValues.push(node.value);
        }

        if (node.children) valueExtracter(node.children);
      });
    
    valueExtracter();
    // update Parent
    this.handleChangeSelection(allValues);
  };

  deselectAll = () => { 
    // Just reset values
    this.handleChangeSelection([]);
  }

  get nodesCount() { 
    const { nodes, noCascade } = this.props;
    let count = 0;

    const counter = (structure = nodes) =>
      structure.forEach(node => {
        const isParentNode = node.hasOwnProperty('children');
        // if parent Node and [ parent should be included in selection ]
        // or if the node [ is Not Parent ] u should Append it
        if ((isParentNode && noCascade) || !isParentNode) {
          count++;
        }

        if (node.children) counter(node.children);
      });

    counter();

    return count;
  }

  render() {
    const { 
      id,
      name,
      value,
      nodes,
      error,
      label,
      classes,
      required,
      disabled,
      noCascade,
      showIcons,
      helperText,
      labelCssClass,
      showExpandAll,
      expandDisabled,
      enableSelectAll,
      optimisticToggle,
      nativeCheckboxes,
      onlyLeafCheckboxes,
    } = this.props;
    const { isSelectAllChecked } = this.state;

    return (
      <div style={{ width: '100%' }}>
        <If condition={label}>
          <InputLabel
            className={classNames(labelCssClass, classes.labelStyles)}
            style={{ fontWeight: 'bold' }}
            htmlFor={`${name}-${id}-input`}
            error={error}
            required={required}
          >
            {label}
          </InputLabel>
        </If>

        <If condition={enableSelectAll}>
          <Checkbox
            name={'selectAll'}
            label={Strings.selectAll}
            withoutHelperText
            value={isSelectAllChecked}
            onChange={(_, value) => this.onSelectAllChange(value)}
          />
        </If>

        <NestedCheckboxTree
          nodes={nodes}
          id={`${name}-${id}`}
          name={`${name}-${id}-input`}
          disabled={disabled}
          checked={value || []}
          noCascade={noCascade}
          showNodeIcon={showIcons}
          showExpandAll={showExpandAll}
          expanded={this.state.expanded}
          expandDisabled={expandDisabled}
          optimisticToggle={optimisticToggle}
          nativeCheckboxes={nativeCheckboxes}
          onlyLeafCheckboxes={onlyLeafCheckboxes}
          onCheck={this.handleChangeSelection}
          onExpand={expanded => this.setState({ expanded })}
          // checkModel={true}
          icons={{
            check: <CheckBoxIcon color={'primary'} />,
            uncheck: <CheckBoxOutlineBlankIcon color={'primary'} />,
            halfCheck: <IndeterminateCheckBoxIcon color={'secondary'} />,
            expandClose: <KeyboardArrowLeftIcon color={'primary'} />,
            expandOpen: <KeyboardArrowDownIcon color={'primary'} />,
            //
            expandAll: <span className="rct-icon rct-icon-expand-all" />,
            collapseAll: <span className="rct-icon rct-icon-collapse-all" />,
            parentClose: <span className="rct-icon rct-icon-parent-close" />,
            parentOpen: <span className="rct-icon rct-icon-parent-open" />,
            leaf: <span className="rct-icon rct-icon-leaf" />
          }}
        />

        <Fade bottom when={error}>
          <FormHelperText
            id={`${name}-${id}-helper-text`}
            error={error}
          >
            {helperText}
          </FormHelperText>
        </Fade>

      </div>
    );
  }
}

CheckboxTree.propTypes = {
  id: PropTypes.string,
  name: PropTypes.string,
  label: PropTypes.string,
  helperText: PropTypes.string,

  error: PropTypes.bool,
  required: PropTypes.bool,
  disabled: PropTypes.bool,
  noCascade: PropTypes.bool,
  showIcons: PropTypes.bool,
  showExpandAll: PropTypes.bool,
  expandDisabled: PropTypes.bool,
  enableSelectAll: PropTypes.bool,
  nativeCheckboxes: PropTypes.bool,
  optimisticToggle: PropTypes.bool,
  onlyLeafCheckboxes: PropTypes.bool,

  value: PropTypes.array,
  nodes: PropTypes.array,

  classes: PropTypes.object,
  labelCssClass: PropTypes.object,

  onChange: PropTypes.func,
};

CheckboxTree.defaultProps = {
  id: '',
  name: '',
  label: '',
  helperText: '',

  error: false,
  disabled: false,
  required: false, // disable the tree [ but the expand buttons will work ]
  noCascade: false, // if [true] when u check a parent node  ---> the children will not be selected
  showIcons: false,
  showExpandAll: false,
  expandDisabled: false,
  enableSelectAll: true,
  nativeCheckboxes: false,
  optimisticToggle: false,// If true, toggling a partially-checked node will select all children. If false, it will deselect.
  onlyLeafCheckboxes: false,

  value: [],
  nodes: [],

  classes: {},
  labelCssClass: {},

  onChange() { }
};

export { CheckboxTree };

`

**Comment by JamesBrightman** [comment]
@MohammedSaberMohammed 
Thanks, my code is quite different to yours but I was able to use your idea of a recursive select all with a manually added Select all checkbox. Here's the example code for mine;
`
const selectAll = () => {
        let results: string[] = [];

        const extractVal = (nodes) => {
            nodes.forEach((e) => {
                results.push((e.value).toString());
                if (e.children) {
                    extractVal(e.children);
                }
            });
        };
        extractVal(nodes); //Being recursion on master node list
        setChecked(results); //Set checkboxes to checked state
    };
`
