### ISSUE TITLE
Icons not showing correctly both in Explorer and Chrome in any settings

### ISSUE THREAD

**Issue by progenysw** [jakezatecky/react-checkbox-tree#256]
**Describe the bug**
In Chrome ,can only see plan black outlines where the checkboxes/icons shd be . In Explorer, cant the 

**Reproduction steps**
Have tried this 

import CheckboxTree from 'react-checkbox-tree';
import 'react-checkbox-tree/lib/react-checkbox-tree.css';
  <CheckboxTree
                                    nodes={this.state.nodes}
                                    checked={checked}
                    
                                    expanded={expanded}
                                    onCheck={this.onCheck}
                                    onExpand={this.onExpand}
                                    showExpandAll={true}
                                    nativeCheckboxes={true}
                                />

and 
fa5 and nativeCheckboxes=false
Have also installed the latest FA set manually .
No compile warnings

**Expected behavior**
I would expect to see colored, correct checkboxes
**Screenshots**
I
![image](https://user-images.githubusercontent.com/56724344/109297825-b73b4e00-7886-11eb-9bc3-dd2c4afd8698.png)
![image](https://user-images.githubusercontent.com/56724344/109297909-e18d0b80-7886-11eb-95da-6fe9211c193a.png)

**Comment by apurva1112** [comment]
I had the same problem. Added below code in my html file and it worked.
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">`

**Comment by jakezatecky** [comment]
As noted, including a link to the CDN should work (including with `iconsClass="fa5"`). Please link to a live email if you still have this issue.
