### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string

### ISSUE THREAD

**Issue by nakamn** [jakezatecky/react-checkbox-tree#257]
Trying to get react-checkbox-tree(1.6.0) to play nicely, but getting the following error in the browser console:

```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports
```

index.js
```
import React from 'react';
import CheckboxTree from 'react-checkbox-tree';
import 'react-checkbox-tree/lib/react-checkbox-tree.css';

const nodes = [{
  value: 'mars',
  label: 'Mars',
  children: [
    { value: 'phobos', label: 'Phobos' },
    { value: 'deimos', label: 'Deimos' },
  ],
}];

class Widget extends React.Component {
  state = {
    checked: [],
    expanded: [],
  };

  render() {
    return (
      <CheckboxTree
        nodes={nodes}
        checked={this.state.checked}
        expanded={this.state.expanded}
        onCheck={checked => this.setState({ checked })}
        onExpand={expanded => this.setState({ expanded })}
      />
    );
  }
}

export default Widget;
```

**Comment by jakezatecky** [comment]
Interesting. There does not seem to be any issue in the code you have written.

Have you used a previous version and had any errors?

I suspect that the bundler you are using (e.g., Webpack) may not be resolving the library correctly. Can you point to a live example with this error or modify [this reference point](https://codesandbox.io/s/react-checkbox-tree-example-forked-xbhh7?file=/src/index.js)?

**Comment by kutsyk-neocles** [comment]
Any update guys? I'm using `webpack` too and hav ethis problem. But no issues with any other libs.

**Comment by jakezatecky** [comment]
Hello @kutsyk-neocles, is it possible for you to create a simplified repo that replicates this error?

**Comment by aniov** [comment]
I'm having same issue (react 16.13) + webpack (4.4.1)

**Comment by jakezatecky** [comment]
Please re-open if this issue persists with the latest version and include a repo/codepen that replicates it.
