### ISSUE TITLE
Navigate through check box tree using arrow keys

### ISSUE THREAD

**Issue by ishakibshaikh** [jakezatecky/react-checkbox-tree#263]
User should be able to navigate in check box tree using up and down arrow keys.

ArrowUp- Navigate to previous node if available.
ArrowDown - Navigate to next node if available.
ArrowRight - Expand parent node if child nodes present.
ArrowLeft - Collapse parent node if child nodes present.

**Comment by jakezatecky** [comment]
Thanks for the report. This is covered under open issue #24.

**Comment by ishakibshaikh** [comment]
Hey,

can you please share the demo link?, I am unable to find it

**Comment by jakezatecky** [comment]
This has not been implemented yet.
