### ISSUE TITLE
Marking of parents with checked leafs

### ISSUE THREAD

**Issue by cvzbynek** [jakezatecky/react-checkbox-tree#272]
Hello,

is there any elegant way to mark parent nodes with checked leafs? I would use node checkboxes, but I need to disable them, because I need only one leaf checked for each closest parent. Which leads me to the next question - is there any solution for restricting selection of leafs within node?

**Comment by jakezatecky** [comment]
For the first question, you could show the parent node but use the `disabled` property on that node to prevent selection but allow leaf selections.

There is no elegant or built-in feature in the checkbox to restrict selection toward a single leaf node,. However, it is possible. After `onCheck` is fired and a leaf is checked, you can modify the `nodes` property` set sibling nodes to `disabled: true`. This would require traversing the original `nodes` tree recursively.
