### ISSUE TITLE
How do I open a child node by default

### ISSUE THREAD

**Issue by GHzhuzhu** [jakezatecky/react-checkbox-tree#292]
When I open a project, I want its list of child nodes to be automatically expanded. 
How do I set this?
![image](https://user-images.githubusercontent.com/60053899/128587303-aa8d09e1-d0aa-4f47-8704-20f1d40451a7.png)
That's the default expansion

**Comment by jakezatecky** [comment]
You can set the `expanded` property to be an array of all of the parent node keys. There is currently no option to expand every available node, but that is a feature that is tracked in another issue slated for a later release.

**Comment by munishchoudhary204** [comment]
Any updates ??

**Comment by jakezatecky** [comment]
You can set an initial value for `expanded` to have the as many levels expanded as you want by utilizing [`expandNodesToLevel`](https://github.com/jakezatecky/react-checkbox-tree#expandnodestolevelnodes-targetlevel). E.g.:

``` jsx
import React, { useState } from 'react';
import CheckboxTree, { expandNodesToLevel } from 'react-checkbox-tree';

// Assuming `nodes` is accessible somewhere, this will open all parent nodes by default
const defaultExpanded = expandNodesToLevel(nodes, Infinity);

function Widget() {
    const [expanded, setExpanded] = useState(defaultExpanded);

    return <CheckboxTree nodes={nodes} expanded={expanded} />;
}
```
