### ISSUE TITLE
How to get complete tree nodes on check 

### ISSUE THREAD

**Issue by suresheprm** [jakezatecky/react-checkbox-tree#293]
How to get all the nodes when check any node

**Comment by jakezatecky** [comment]
Since you initialize the React component with a `nodes` property, you should be able to get the complete list of nodes from wherever you sourced them from. The event handlers for the CheckboxTree do not return the full list of nodes.

**Comment by suresheprm** [comment]
Thanks Jake. Will do the same and i got my result.
