### ISSUE TITLE
Suggestions: how do i customise the UI of the React-check-box-tree

### ISSUE THREAD

**Issue by bgreatfit** [jakezatecky/react-checkbox-tree#294]
Any pointer? thanks

**Comment by jakezatecky** [comment]
The primary way is through adding CSS rules. You can look at the [source Sass file](https://github.com/jakezatecky/react-checkbox-tree/blob/master/src/scss/react-checkbox-tree.scss#L14) to get an idea of what styles the component uses.

**Comment by worlderland** [comment]
I tried the usual methods of styling in React but the css file was still overriding my styles. So I copied the css stylesheet locally in my component's folder, pointed the component to it and worked on the styles as I pleased.
