### ISSUE TITLE
Override CSS property without changing node_module files

### ISSUE THREAD

**Issue by SergioArrighi** [jakezatecky/react-checkbox-tree#300]
Hello, 

I'd like to change
`display: flex`
to
`display: inline-flex`

If I simply change the files any new installation of my app will not profit of this change.
How can I override this particular property only?

I'm using React Bootstrap and my code looks like this
`<React.Fragment>
    <Container>
        <Row>
            <Col>
                <input
                    placeholder="🔎 Search..."
                    type="text"
                    value={filterText}
                    onChange={onFilterChange}
                />
            </Col>
        </Row>
        <Row>
            <Col>
                <CheckboxTree
                    noCascade
                    checked={checked}
                    expanded={expanded}
                    iconsClass="fa5"
                    nodes={nodesFiltered}
                    onCheck={onCheck}
                    onExpand={onExpand}
                    onClick={onClick}
                />
            </Col>
        </Row>
        <Row>
            <Col>
                <strong>Clicked Node</strong>: {(clicked && clicked.value) || notClickedText}
            </Col>
        </Row>
    </Container>
</React.Fragment>`

I tried adding
` style={{display: 'inline-flex'}}`
To the CheckboxTree element

But looking in the browser I can see that this doesn't get applied.

Thanks for the awesome library and best regards!

**Comment by fre-ben** [comment]
How did you fix this?

**Comment by jakezatecky** [comment]
There is no `style` property for the CheckboxTree component. This is in large part because the tree has multiple DOM elements below it and it is not feasible to provide a style access to each of those nested elements.

The most straightforward way to change any of the styling is to supply your own CSS that defines any overrides. For example:

``` css
.react-checkbox-tree {
  display: inline-flex;
}
```
