### ISSUE TITLE
Suggestion: Would be cool to be able to set different icons for different nodes' children (image icon, file icon, and so on)

### ISSUE THREAD

**Issue by worlderland** [jakezatecky/react-checkbox-tree#308]
A cool feature would be showing different icons for nodes' children:

- Fruit (folder
- - Apple icon
- - Lemon Icon
- - Orange icon
- Veggie
- - Tomato icon
- - Lettuce icon
- - .....

At the moment the representation is parent (node) = folder icon, child (file) =file icon, but not all children are files. :)

**Comment by jakezatecky** [comment]
An individual note supports the [`icon`](https://github.com/jakezatecky/react-checkbox-tree#node-properties) property. You can also reference the [`CustomIconsExample`](https://github.com/jakezatecky/react-checkbox-tree/blob/master/examples/src/js/CustomIconsExample.js) file to see how that works in practice.
