### ISSUE TITLE
Using this tree in a form

### ISSUE THREAD

**Issue by RodrigoCarvalho21** [jakezatecky/react-checkbox-tree#31]
Good morning,

Using this tree inside a form is triggering the submit action each time that I expand the tree at any level.

There's any way to avoid this issue? Or there's something wrong about my tree configuration?

Thanks for the help.

**Comment by jakezatecky** [comment]
Thanks for the report @RodrigoCarvalho21! I went ahead and also published a new version in npm containing this bugfix.
