### ISSUE TITLE
Custom CSS per node

### ISSUE THREAD

**Issue by RodrigoCarvalho21** [jakezatecky/react-checkbox-tree#32]
Good morning,

Are you planning to do css customization in terms of nodes, like what you have with icons? I think it's a good thing to have in this context, putting classNames on the nodes so you can customise the look of each node. 

Thanks for the active development on this component :)

**Comment by jakezatecky** [comment]
It would not be difficult to support a `className` property in the `nodes` object. I can add something to allow developers to append classes to any given node, sure.
