### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by RodrigoCarvalho21** [jakezatecky/react-checkbox-tree#33]
Good afternoon,

I updated this component on my package.json and did the "npm install" like the normal process.
Although the component still doesn't have the type button in there, I can see in your code but in the compiled code (lib folder in the node modules), the type doesn't show up.

There's something wrong in the build process or I need to do something else to update? 

(I already cleaned npm caches)

Thanks for the help!

**Comment by jakezatecky** [comment]
Wow, you are right. Somehow I managed to publish without the updated `./lib` folder. I apologize for that.

I added a `prepublishOnly` event to prevent this from happening again.

**Comment by RodrigoCarvalho21** [comment]
It's alright, thanks for the big help and support!
