### ISSUE TITLE
Hi doubts about some features

### ISSUE THREAD

**Issue by shashika18923** [jakezatecky/react-checkbox-tree#333]
Please include a clear and concise description of the feature or enhancement you would like to have added to the project.
Hi,

I'm going to use this tree view component for my project sir, before that I have some doubts to clarify,
1. is this component support to the lazy loading 
2.  is this component have functions to identify node by giving its id as an example finding parent node of specific children node.
3.  can we change the image icon of the elements.
4. is this component supporting to hooks

those are the doubts and still waiting for your respective reply 

thank you,
shashika

**Comment by jakezatecky** [comment]
1. No support for lazy-loading yet
2. No pre-built search functions, but you can use `node.parent` when the `onCheck` event fires
3. Yes, all icons can be changed using the `icons` property
4. There are no built-in hooks for this component
