### ISSUE TITLE
Allow expand but disable check box selection

### ISSUE THREAD

**Issue by mtskm** [jakezatecky/react-checkbox-tree#36]
Disabled property is disabling the whole component. Is there a way to have expand feature enabled and have check box selection disabled?

**Comment by jakezatecky** [comment]
I am not quite sure what issue you are having, as the `disabled` property only disables the ability to toggle checkboxes. You can still expand/collapse parent nodes when `disabled` is passed to the component. If you want to disable expanding behavior you pass in `expandDisabled`.

**Comment by mtskm** [comment]
Thank you, got it working.

**Comment by jakezatecky** [comment]
Glad to hear it!

**Comment by 7ruth** [comment]
Is there a way to disabled checkboxes on some of the children instead of the whole tree?

**Comment by 7ruth** [comment]
NVM found it! For anyone else: 

``` 
nodes={[
                             {
                                 value: 'ex1',
                                 label: 'ex1',
                                 disabled: true,
                                 children: [
                                     { value: 'ex1.1', label: 'ex1.1' },
                                 ],
                             },
                         ]} 
```
