### ISSUE TITLE
Collapse node problem with next js

### ISSUE THREAD

**Issue by eshad** [jakezatecky/react-checkbox-tree#364]
### **Node Collapse Problem**
After integrating into next app node collapses after hitting check 
2nd time attempts of expanding node makes checkbox uncheck again... 

> Getting checked or expanded values accurately 

**Codesandbox**
This is how i tried to solve: [Sandbox](https://codesandbox.io/s/next-js-forked-0vxydb)

**Expected Output of this to get nodes exact value with checked**

>**Node Object:**
```JS
const nodes:any = [{
        value: 'mars',
        label: 'Mars',
        children: [
            { value: 'phobos', label: 'Phobos' },
            { value: 'deimos', label: 'Deimos' },
        ],
    }];
```

>**State controlling:**
```JS 
let [state, setState]:any = useState([{
        checked: [],
        expanded: [],
    }]);
```

>**Component placement:**
 ```JS
<CheckboxTree
                nodes={nodes}
                iconsClass="fa5"
                optimisticToggle
                showExpandAll
                checked={state.checked}
                expanded={state.expanded}
                onExpand={expanded => setState((e)=>[...state, {expanded: e} ])}
                onCheck={checked => setState([(c)=> [...state, {checked: c}])}
/>
```

![react-checkbox](https://user-images.githubusercontent.com/4688406/179395771-2952c223-7f47-4be4-970f-3218a4626e9b.png)

@ai @RusAlex @koszti @thespooler @karaxuna

**Comment by jakezatecky** [comment]
Your CodeSandbox example does not render the initial tree. When I modified it do to so, I noticed that you were losing the `selected` or `checked` state value by not merging with the previous state.

See my modification of your CodeSandbox [here](https://codesandbox.io/s/next-js-forked-zu0w0l?file=/index.tsx), which works as expected.
