### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by nolatone** [jakezatecky/react-checkbox-tree#387]
Given this function in CheckBoxTree.js:

`    onCheck(nodeInfo) {
        const { checkModel, noCascade, onCheck } = this.props;
        const model = this.state.model.clone();
        const node = model.getNode(nodeInfo.value);

        model.toggleChecked(nodeInfo, nodeInfo.checked, checkModel, noCascade);
        onCheck(model.serializeList('checked'), { ...node, ...nodeInfo });
    }`

In the line:
onCheck(model.serializeList('checked'), { ...node, ...nodeInfo });

What is the second argument to onCheck for? This part: **_{ ...node, ...nodeInfo }_**

I'm not seeing that it does anything. The onCheck only takes the list of nodes returned by model.serializeList().

**Comment by jakezatecky** [comment]
The component supplies the second parameter in case the developer wants to know which node triggered this change. This was a feature request I received some time back.
