### ISSUE TITLE
Tooltips for individual nodes in HTML

### ISSUE THREAD

**Issue by mshiraguppi** [jakezatecky/react-checkbox-tree#392]
How do I set tooltips for individual nodes in HTML without using <TreeNode>? Is there a way to modify "nodes" property? By the way, is "NodeLabelProps" property retired?

**Comment by jakezatecky** [comment]
You can set the `title` property for a node. Take a look at the [**Node Properties**](https://github.com/jakezatecky/react-checkbox-tree#node-properties) section of the documents.

Not sure what you mean on `NodeLabelProps`. The `label` value can be a JSX node if you want something custom and not just text.

**Comment by mshiraguppi** [comment]
Thanks Jake. With the title property, the tool tip is shown as string. So, if I include HTML tags for title they are shown as is. I got the following snippet. Here data array is being looped through and each item represents one node. I tried with title properties which are commented out. 
title: d['Tooltip'] ?? null -- here the html tags are shown as strings. 
title: <span dangerouslySetInnerHTML={{ __html: d['Tooltip'] }} />, ---- doesn't work
 nodeLabelProps: {
                title: <div>Tooltip for node 1</div>,
                style: { display: 'inline-block' },
            }, ----- doesn't work.

data?.forEach((d) => {
        const item = {
            ...d,
            id: d[idKey] ?? d.id ?? null,
            parent: d[parentKey] ?? d.parent ?? null,
            label: d[labelKey] ?? d.label ?? null,
            value: d[idKey] ?? d.id ?? null,
            //title: d['Tooltip'] ?? null,
            //title: <span dangerouslySetInnerHTML={{ __html: d['Tooltip'] }} />,
            nodeLabelProps: {
                title: <div>Tooltip for node 1</div>,
                style: { display: 'inline-block' },
            },
        };

Could you please provide me a sample? I don't want to use <TreeNode> as child element of <CheckboxTree>. This was another sample example I got from google.  
Thanks

**Comment by jakezatecky** [comment]
The `title` property just sets the HTML `title` property, which only renders text.

If you want JSX/HTML in your tooltip, you will have to use some tooltip library (such as [`react-tooltip`](https://github.com/ReactTooltip/react-tooltip#readme)) and supply the `label` property with the JSX necessary for both the label and the tooltip.
