### ISSUE TITLE
How can I add a tooltip for the elements inside the tree?

### ISSUE THREAD

**Issue by adelmemariani** [jakezatecky/react-checkbox-tree#396]
Hi,

Thank you for your great work!

I wonder if I can add a tooltip (a popup to show some explanation) to the tree items.
As far as I understood, we pass the nodes to the component, but I want to add a new icon (or button) to the items and show the tooltip after mouse-over event.

Is it possible to add HTML tags in the items?

Thank you for your consideration :)

**Comment by jakezatecky** [comment]
The `label` property for each node can be a JSX element, so instead of simply supplying text, you can pass a more advanced node and use a library such as [React Tooltip](https://github.com/ReactTooltip/react-tooltip) to render whatever tooltip you desire.

**Comment by adelmemariani** [comment]
> The `label` property for each node can be a JSX element, so instead of simply supplying text, you can pass a more advanced node and use a library such as [React Tooltip](https://github.com/ReactTooltip/react-tooltip) to render whatever tooltip you desire.

That's wonderful. Thank you for your answer :)

**Comment by jakezatecky** [comment]
Closing as resolved. Let me know if further help is required.
