### ISSUE TITLE
multiple checkbox selection disable

### ISSUE THREAD

**Issue by niku2021** [jakezatecky/react-checkbox-tree#403]
Is there a way to disable multiple checkbox selection disable. I want to checked one at a time

**Comment by jakezatecky** [comment]
Are you asking if there is a way to disable the behavior of checking a parent and propagating that to its children, or are you asking for there to be only one node checked at a time, like a radio button (as opposed to a list of checkboxes)?

You can disable the former by passing the `noCascade` property. The latter is not quite supported yet.

**Comment by niku2021** [comment]
I am asking only one node checked at a time, like a radio button (as opposed to a list of checkboxes) this one

**Comment by niku2021** [comment]
this fixed my issue
[https://stackoverflow.com/questions/75220051/disable-multiple-select-in-checkbox-treeview-in-react/75230441#75230441](url)
