### ISSUE TITLE
Version 0.6.3 does not include disabled and expandDisabled props in /lib/index.js

### ISSUE THREAD

**Issue by carlosu4** [jakezatecky/react-checkbox-tree#42]
Hi, i'm trying to use the component (version 0.6.3) downloaded from NPM and I can not use the disabled and expandDisabled new properties. I have tried searching for them in /lib/index.js with no results obtained.

Is this a bug or should I import the library in some other way?

**Comment by jakezatecky** [comment]
Wow, you are right. Somehow the npm version managed to get updated without this feature being included in `lib/index.js`. I just pushed a fix, v0.6.4, that I have verified does have these properties. Sorry about that.
