### ISSUE TITLE
Enable the check only at last level parent node and child nodes

### ISSUE THREAD

**Issue by manjunathangv** [jakezatecky/react-checkbox-tree#438]
How should I include a check only at last level parent node and its child node. Checkbox should not be at all nodes.

Something like this.

![image](https://github.com/jakezatecky/react-checkbox-tree/assets/54570517/9753027b-f946-4b65-b79d-4a7194e1f2f6)

Please also help, if its already supported.

**Comment by jakezatecky** [comment]
You can achieve this by setting `showCheckbox: false` to any non-final parent nodes. Note that you would have to recursively iterate through the `nodes` object yourself to set this property, as the feature you are requesting is not natively supported.

**Comment by manjunathangv** [comment]
Thanks for your reply and suggestion.

It helped to add checkbox only at last level parent using `showCheckbox: true or false`.
