### ISSUE TITLE
Can this be used with Immutable Data

### ISSUE THREAD

**Issue by t-hughes** [jakezatecky/react-checkbox-tree#45]
Can this be used with immutable data? Such as defining the data(nodes, labels, etc.) in another folder/file and bringing it in?

**Comment by jakezatecky** [comment]
I am afraid I am not quite sure what you are asking. The component itself does not (or at least it should not) mutate any data passed into it, including `nodes` array. If you define the data in another file and import it, that should not be an issue.

``` jsx
import { myAwesomeTreeNodes } from './tree-structures.js';

...

<CheckboxTree nodes={myAwesomeTreeNodes} />
```

If you are talking about something like [Immutable.js](https://github.com/facebook/immutable-js/), then this component does not support that directly, as it expects a more traditional array/object composition. But libraries like Immutable have a `toArray()` which would return the object in the format expected by the component.

**Comment by t-hughes** [comment]
Thank you for your quick response 👍
