### ISSUE TITLE
Get ID

### ISSUE THREAD

**Issue by mftlhn** [jakezatecky/react-checkbox-tree#489]
How can I get the ID of the checkbox I checked. It's just the checkbox I'm checking. Not all the checkboxes have been checked?

**Comment by jakezatecky** [comment]
The second parameter of the `onCheck` function function is the node the triggered the check. E.g.:

``` jsx
const onCheck = (checked, targetNode) => {
  console.log(targetNode.value);
};

return (
  <CheckboxTree
    ...
    onCheck={onCheck}
  />
);
```

**Comment by mftlhn** [comment]
thanks it works
