### ISSUE TITLE
Disable Parent checkbox if have children checkbox

### ISSUE THREAD

**Issue by MuhRiswan** [jakezatecky/react-checkbox-tree#490]
How to prevent a parent checkbox from being displayed if there are children in it?

**Comment by jakezatecky** [comment]
There is no direct option to remove parent checkboxes if any child has a checkbox, but you have the following options.

* Checkboxes can be hidden on a node-level by setting `showCheckbox: false` for any given node.
* They can also be hidden by the passing the `onlyLeafCheckboxes` property to the tree, which will force checkboxes to render only on leaf nodes.

**Comment by MuhRiswan** [comment]
thanks sir for answer, i have fix this problem with custome API to add showCheckbox and condition.
