### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by williamboman** [jakezatecky/react-checkbox-tree#5]
Getting `Fatal undefined` error when running `build-style` gulp task.

```sh
$ uname
Darwin
$ npm version
{ 'react-checkbox-tree': '0.2.0',
  npm: '2.15.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.5.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '4.5.103.37',
  zlib: '1.2.8' }
```

**Comment by williamboman** [comment]
Looks like [L45-L46](https://github.com/jakezatecky/react-checkbox-tree/blob/1c5f76f2377207298e8e13a9365d4d40208be539/gulpfile.js#L45-L46) in `gulpfile.js` is the culprit.

**Comment by jakezatecky** [comment]
Might be because the wrong Ruby gem was specified. Can you see if 44c07156cdeaa4003616ef432710c828c4292ed4 resolves the linting issues for you?

**Comment by williamboman** [comment]
> Might be because the wrong Ruby gem was specified. Can you see if 44c0715 resolves the linting issues for you?

Doh, didn't notice RubySass was used, my bad. Would you oppose switching to libsass (NodeSass) to avoid the Ruby dependency?

**Comment by williamboman** [comment]
Case of RTFM, closing.
