### ISSUE TITLE
CSS issues with React Checkbox tree

### ISSUE THREAD

**Issue by ArunTej37** [jakezatecky/react-checkbox-tree#66]
Hi Jake,

   Am facing CSS issues in my development as it is adding some additional spans between Toggle and the Node text. Am using the "react-checkbox-tree" CSS file. 
  
Following are the html of the spans am getting additionally.

span class="rct-checkbox" span class="rct-icon rct-icon-check"
span class="rct-node-icon" span class="rct-icon rct-icon-parent-open"

  Attaching the screenshot for the reference.
  Please do the needful. Thanks in advance.

![additional spans_react checkbox tree](https://user-images.githubusercontent.com/35249768/34706986-aef9ec52-f502-11e7-98ab-4977b4d572ab.JPG)

**Comment by jakezatecky** [comment]
Hmm, it also looks as if the CSS styles are not quite getting applied or are getting overridden by something else (possibly some `!important` rules). Those spans are part of the main component, and the underlying HTML checkboxes are supposed to be hidden. Can you point to a live example of the issue you are experiencing?

**Comment by ArunTej37** [comment]
Thank you Jake for your reply. It get fixed by changing the following classes.
1) .react-checkbox-tree input - Removed display property.
2). Removed content property in the following classes.
.rct-icon-uncheck::before 
.rct-icon-check::before 
.rct-icon-half-check::before
.rct-icon-leaf::before 
.rct-icon-parent-open::before
.rct-icon-parent-close::before
