### ISSUE TITLE
onCheck should also return the clicked node

### ISSUE THREAD

**Issue by tnargib** [jakezatecky/react-checkbox-tree#72]
It would be great if the onCheck callback return at the same time the new checked array AND the selected node value so we can control more properly changes on the tree.

For now I am only capable of detect changes on the last level but I would like to be able to tell if the item that was clicked was the one at the top level

**Comment by tnargib** [comment]
After all the modification is really simple. I got the wanted behaviour by returning the node parameter in the onCheck function in CheckboxTree.js : 
```
onCheck(node) {
        const { noCascade, onCheck } = this.props;

        this.toggleChecked(node, node.checked, noCascade);
        onCheck(this.serializeList('checked'), node);
}
```

If you mind I can make a pull request to add the feature

**Comment by airowe** [comment]
@tnargib How did you pass the entire node to your click handler? I'm only seeing a way to pass the value of the node.

**Comment by airowe** [comment]
How can we intercept the node value here? I'm needing to grab the label out of the checked nodes and pass them to my redux store.

**Comment by jakezatecky** [comment]
Somehow I never saw the follow up question. The node value is available via `node.value`, but the label is not directly accessible. If it is desired to have all of the node data accessible in this parameter, I can amend it to return the raw node data.
