### ISSUE TITLE
How to show all the elements as links 

### ISSUE THREAD

**Issue by VikramMaiya** [jakezatecky/react-checkbox-tree#75]
Hi, Instead of checkbox, I want to make the elements as clickable links and give the elements a on click property. and onclick() function should have the same functionality as onCheck.

**Comment by jakezatecky** [comment]
There is no way currently to do this, but it would not be too terribly difficult to add. I'll leave this open as an enhancement that might be later added to the component.

**Comment by jakezatecky** [comment]
#86. Apparently I'm a scrub at closing multiple issues in a single commit.
