### ISSUE TITLE
Expand All/Collapse All?

### ISSUE THREAD

**Issue by airowe** [jakezatecky/react-checkbox-tree#79]
Is there any easy way to expand all and/or collapse all nodes without iterating through all the children nodes and adding their values to the expanded array (or clearing it)?

**Comment by jakezatecky** [comment]
There is not any method currently built into the component to do this. Yes, you would have to iterate through all of the nodes and their children.

This could be added to the component, possibly as a utility function or as a control, potentially near the top of the component, that allows the user to easily expand/collapse all (as well as check/uncheck all).

**Comment by LucasPickering** [comment]
I'd be very interested in a check/uncheck all feature (and expand/collapse all to a lesser extent too). Do you have any plans for this in the future?

**Comment by jakezatecky** [comment]
@LucasPickering the check/uncheck all can be achieved by having a single root level node. You can expand the root by default so that the tree is functionally similar to what you originally had, and checking/unchecking the root will effectively achieve what you are asking.
