### ISSUE TITLE
Does not work with mobx observable

### ISSUE THREAD

**Issue by ertejaspatel** [jakezatecky/react-checkbox-tree#83]
Failed prop type: Invalid prop `checked` of type `object` supplied to `CheckboxTree`, expected an array

**Comment by jakezatecky** [comment]
Yes, primitive array types are expect for the `checked` property. If the Mobx observable can fully emulate array-like functionality, then I would be open to amending the prop types validation to support it as appropriate, but since I do not use Mobx, I do not know how that would be achieved.

**Comment by jogoodma** [comment]
@ertejaspatel, the way to handle this with Mobx is to make a shallow copy of the array with `array.slice()` and pass that to the `checked` prop.  If @jakezatecky added the the [Mobx PropTypes](https://github.com/mobxjs/mobx-react#proptypes) you would be passing observables to a non observer component, which could lead to issues.

**Comment by jakezatecky** [comment]
Closing per @jogoodma's explanation. If other people feel that this is worth discussion, I can re-open, but the explanation seems reasonable enough.
